package your.project.templatebot.embeds;

import your.project.templatebot.main.Main;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.MessageEmbed;

import java.awt.*;
import java.time.OffsetDateTime;

public class embedCreator {

    //adds the default things every embed has
    public static void defaultAdder(EmbedBuilder embed) {
        embed.setFooter("Generated by " + Main.configReader("name"))
                //change the hex code to change the color of the bots embeds
                .setColor(new Color(0xC68C59))
                .setTimestamp(OffsetDateTime.now());
    }

    //the default embed which is used in most cases when the bot answers to a slash command
    public static MessageEmbed defaultEmbed(String title, String description) {
        EmbedBuilder embed = new EmbedBuilder();
        embed.setDescription(description)
                .setTitle(title);
        defaultAdder(embed);
        return embed.build();
    }

}
